=== bfansports/CloudTranscode/pollers/json_schemas/presets.json
{
    "id": "http://sport-archive.com/input-schema/presets#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Schemas for video presets",
    "type": "object",
    "properties": {
	"name": {
	    "description": "Preset name",
	    "type": "string",
	    "minLength": 3,
	    "maxLength": 128
	},
	"description": {
	    "description": "Preset description",
	    "type": "string",
	    "minLength": 1,
	    "maxLength": 512
	},
	"size": {
	    "description": "Video size",
	    "type": "string",
	    "pattern": "^[0-9]{1,5}x[0-9]{1,5}+$"
	},
	"frame_rate": {
	    "description": "Video frame rate",
	    "type": "number"
	},
	"video_bitrate": {
	    "description": "Video bitrate",
	    "type": "string",
	    "pattern": "^[0-9]{1,6}k$"
	},
	"audio_bitrate": {
	    "description": "Audio bitrate",
	    "type": "string",
	    "pattern": "^[0-9]{1,6}k$"
	},
	"video_codec": {
	    "description": "Video codec",
	    "type": "string",
	    "minLength": 3,
	    "maxLength": 64
	},
	"audio_codec": {
	    "description": "Audio codec",
	    "type": "string",
	    "minLength": 3,
	    "maxLength": 64
	},
	"video_codec_options": {
	    "description": "Video codec options",
	    "type": "string",
	    "minLength": 3,
	    "maxLength": 256
	}
    },
    "required": ["name", "description", "size", "frame_rate", "video_bitrate", "audio_bitrate", "video_codec", "audio_codec"],
    "additionalProperties": false
}

=== bfansports/CloudTranscode/config/presets/360p-4.3-generic.json
{
    "name": "System preset: Generic 360p 4:3",
    "description": "Generic 360p 4:3 transcoding preset",
    "size": "480x360",
    "frame_rate": 29.97,
    "video_bitrate": "600k",
    "audio_bitrate": "128k",
    "video_codec": "libx264",
    "audio_codec": "libfdk_aac",
    "video_codec_options": "MaxReferenceFrames:3,Profile:baseline,Level:3"
}

=== bfansports/CloudTranscode/config/presets/kindleFire-generic.json
{
    "name": "System preset: Generic KindleFire",
    "description": "Generic transcoding preset for Kindle Fire",
    "size": "1024x576",
    "frame_rate": 30,
    "video_bitrate": "1600k",
    "audio_bitrate": "160k",
    "video_codec": "libx264",
    "audio_codec": "libfdk_aac",
    "video_codec_options": "MaxReferenceFrames:3,Profile:main,Level:3.1"
}

=== bfansports/CloudTranscode/config/presets/appleTV3G-generic.json
{
    "name": "System preset: Generic Apple TV 3G",
    "description": "Generic transcoding preset for: Apple TV 3G, Roku HD/2 XD",
    "size": "1920x1080",
    "frame_rate": 30,
    "video_bitrate": "5000k",
    "audio_bitrate": "160k",
    "video_codec": "libx264",
    "audio_codec": "libfdk_aac",
    "video_codec_options": "MaxReferenceFrames:3,Profile:high,Level:4"
}

=== bfansports/CloudTranscode/config/presets/320x240-generic.json
{
    "name": "System preset: Generic 320x240",
    "description": "Generic 320x240 transcoding preset",
    "size": "320x240",
    "frame_rate": 21,
    "video_bitrate": "300k",
    "audio_bitrate": "64k",
    "video_codec": "libx264",
    "audio_codec": "libfdk_aac",
    "video_codec_options": "MaxReferenceFrames:3,Profile:baseline,Level:1.3"
}

=== bfansports/CloudTranscode/config/presets/iphone4S-generic.json
{
    "name": "System preset: Generic iphone4S",
    "description": "Generic transcoding preset for: iPhone 4s and above, iPad 3G and above, iPad mini, Samsung Galaxy S2/S3/Tab 2",
    "size": "1920x1080",
    "frame_rate": 30,
    "video_bitrate": "5000k",
    "audio_bitrate": "160k",
    "video_codec": "libx264",
    "audio_codec": "libfdk_aac",
    "video_codec_options": "MaxReferenceFrames:3,Profile:high,Level:4.1"
}

=== bfansports/CloudTranscode/config/presets/kindleFireHD8.9-generic.json
{
    "name": "System preset: Generic KindleFireHD8.9",
    "description": "Generic transcoding preset for Kindle Fire HD 8.9",
    "size": "1920x1080",
    "frame_rate": 30,
    "video_bitrate": "5400k",
    "audio_bitrate": "160k",
    "video_codec": "libx264",
    "audio_codec": "libfdk_aac",
    "video_codec_options": "MaxReferenceFrames:3,Profile:main,Level:4"
}

=== bfansports/CloudTranscode/config/presets/iphone3GS-generic.json
{
    "name": "System preset: Generic iphone3GS",
    "description": "Generic transcoding preset for: iPhone 3GS",
    "size": "640x480",
    "frame_rate": 30,
    "video_bitrate": "600k",
    "audio_bitrate": "128k",
    "video_codec": "libx264",
    "audio_codec": "libfdk_aac",
    "video_codec_options": "MaxReferenceFrames:3,Profile:baseline,Level:3"
}

=== bfansports/CloudTranscode/config/presets/720p-generic.json
{
    "name": "System preset: Generic 720p",
    "description": "Generic 720p transcoding preset",
    "size": "1280x720",
    "frame_rate": 29.97,
    "video_bitrate": "2400k",
    "audio_bitrate": "160k",
    "video_codec": "libx264",
    "audio_codec": "libfdk_aac",
    "video_codec_options": "MaxReferenceFrames:3,Profile:baseline,Level:3.1"
}
