=== bfansports/CloudTranscode/pollers/json_schemas/presets.json
{
    "id": "http://sport-archive.com/input-schema/presets#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Schemas for video presets",
    "type": "object",
    "properties": {
	"name": {
	    "description": "Preset name",
	    "type": "string",
	    "minLength": 3,
	    "maxLength": 128
	},
	"description": {
	    "description": "Preset description",
	    "type": "string",
	    "minLength": 1,
	    "maxLength": 512
	},
	"size": {
	    "description": "Video size",
	    "type": "string",
	    "pattern": "^[0-9]{1,5}x[0-9]{1,5}+$"
	},
	"frame_rate": {
	    "description": "Video frame rate",
	    "type": "number"
	},
	"video_bitrate": {
	    "description": "Video bitrate",
	    "type": "string",
	    "pattern": "^[0-9]{1,6}k$"
	},
	"audio_bitrate": {
	    "description": "Audio bitrate",
	    "type": "string",
	    "pattern": "^[0-9]{1,6}k$"
	},
	"video_codec": {
	    "description": "Video codec",
	    "type": "string",
	    "minLength": 3,
	    "maxLength": 64
	},
	"audio_codec": {
	    "description": "Audio codec",
	    "type": "string",
	    "minLength": 3,
	    "maxLength": 64
	},
	"video_codec_options": {
	    "description": "Video codec options",
	    "type": "string",
	    "minLength": 3,
	    "maxLength": 256
	}
    },
    "required": ["name", "description", "size", "frame_rate", "video_bitrate", "audio_bitrate", "video_codec", "audio_codec"],
    "additionalProperties": false
}

=== bfansports/CloudTranscode/config/presets/appleTV2G-generic.json
{
    "name": "System preset: Generic Apple TV 2G",
    "description": "Generic transcoding preset for Apple TV 2G",
    "size": "1280x720",
    "frame_rate": 30,
    "video_bitrate": "5000k",
    "audio_bitrate": "160k",
    "video_codec": "libx264",
    "audio_codec": "libfdk_aac",
    "video_codec_options": "MaxReferenceFrames:3,Profile:main,Level:3.1"
}

=== bfansports/CloudTranscode/config/presets/iphone4-generic.json
{
    "name": "System preset: Generic iphone4",
    "description": "Generic transcoding preset for: iPod touch 5G, 4G, iPad 1G, 2G",
    "size": "1280x720",
    "frame_rate": 30,
    "video_bitrate": "2200k",
    "audio_bitrate": "160k",
    "video_codec": "libx264",
    "audio_codec": "libfdk_aac",
    "video_codec_options": "MaxReferenceFrames:3,Profile:main,Level:3.1"
}

=== bfansports/CloudTranscode/config/presets/web-generic.json
{
    "name": "System preset: Generic Web",
    "description": "Generic transcoding preset for: Facebook, SmugMug, Vimeo, YouTube",
    "size": "1280x720",
    "frame_rate": 30,
    "video_bitrate": "2200k",
    "audio_bitrate": "160k",
    "video_codec": "libx264",
    "audio_codec": "libfdk_aac",
    "video_codec_options": "MaxReferenceFrames:3,Profile:main,Level:3.1"
}

=== bfansports/CloudTranscode/config/presets/ipodTouch-generic.json
{
    "name": "System preset: Generic iPod Touch",
    "description": "Generic transcoding preset for: iPhone 1, 3, iPod classic",
    "size": "640x480",
    "frame_rate": 30,
    "video_bitrate": "1500k",
    "audio_bitrate": "128k",
    "video_codec": "libx264",
    "audio_codec": "libfdk_aac",
    "video_codec_options": "MaxReferenceFrames:3,Profile:baseline,Level:3"
}

=== bfansports/CloudTranscode/config/presets/kindleFireHD-generic.json
{
    "name": "System preset: Generic KindleFireHD",
    "description": "Generic transcoding preset for Kindle Fire HD",
    "size": "1280x720",
    "frame_rate": 30,
    "video_bitrate": "2200k",
    "audio_bitrate": "160k",
    "video_codec": "libx264",
    "audio_codec": "libfdk_aac",
    "video_codec_options": "MaxReferenceFrames:3,Profile:main,Level:4"
}
