=== bfansports/CloudTranscode/src/activities/schemas/ValidateInputAndAsset.json
{
    "id": "http://sport-archive.com/input-schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Schema for ValidateInputAndAsset activity task",
    "type": "object",
    "properties": {
        "api_key": {
            "description": "API for your Cloud Transcode account",
            "type": "string"
        },
        "input_type": {
            "enum": [ "VIDEO", "AUDIO", "IMG", "DOC" ],
            "description": "Type of the input file to transcode: VIDEO, AUDIO, DOC, IMG",
            "type": "string"
        },
        "input_bucket": {
            "description": "S3 bucket where the file is located",
            "type": "string"
        },
        "input_file": {
            "description": "Path to the file to process",
            "type": "string"
        },
        "job_label": {
            "description": "Name to your job",
            "type": "string"
        },
        "outputs": {
            "description": "List of all the outputs needed for that job array of max 100 entries",
            "type": "array",
            "items": {
                "$ref": "output/base.json",
                "oneOf": [                    
                    { "$ref": "output/video.json" },
		    { "$ref": "output/thumb.json" }
                ]
            },
            "minItems": 1,
            "uniqueItems": true
        }
    },
    "required": ["api_key", "input_type", "input_bucket", "input_file", "outputs"],
    "additionalProperties": true
}

=== bfansports/CloudTranscode/input_samples/input_thumbs2.json
{
    "api_key": "1234567890abcdefghijkl",
    "input_type": "VIDEO",
    "input_bucket": "ct-my-bucket-in",
    "input_file": "/input2/test2.mp4",
    "job_label": "test2 thumbnails",
    "outputs": [
	{
	    "output_type": "THUMB",
	    "mode": "intervals",
	    "output_bucket": "ct-my-bucket-out",
	    "output_file": "/output1/thumbs_interval/test1_thumb.png",
	    "s3_rrs": true,
	    "s3_encrypt": true,
	    "size": "160x120",
	    "intervals": 5
	}
    ]
}

=== bfansports/CloudTranscode/input_samples/input_video2.json
{
    "api_key": "1234567890abcdefghijkl",
    "input_type": "VIDEO",
    "input_bucket": "ct-my-bucket-in",
    "input_file": "/input2/test2.mp4",
    "job_label": "test2 transcode",
    "outputs": 
    [
	{
	    "output_type": "VIDEO",
	    "output_label": "SD smartphone test2 output",
	    "output_bucket": "ct-my-bucket-out",
	    "output_file": "/output2/test2_sd_phone.mp4",
	    "s3_rrs": true,
	    "s3_encrypt": false,
	    "preset": "480p-16.9-generic",
	    "no_enlarge": false,
	    "watermark": {
		"input_bucket": "ct-my-bucket-in",
		"input_file": "/watermark/logo_SA.png",
		"size": "75.2x28.4",
		"opacity": 2,
		"x": 20,
		"y": 20
	    }
	},
	{
	    "output_type": "VIDEO",
	    "output_label": "HD smartphone test2 output",
	    "output_bucket": "ct-my-bucket-out",
	    "output_file": "/output2/test2_hd_phone.mp4",
	    "s3_rrs": false,
	    "s3_encrypt": true,
	    "preset": "1080p-generic",
	    "no_enlarge": false,
	    "watermark": {
		"input_bucket": "ct-my-bucket-in",
		"input_file": "/watermark/logo_SA.png",
		"size": "75.2x28.4",
		"opacity": 2,
		"x": 20,
		"y": 20
	    }
	},
	{
	    "output_type": "THUMB",
	    "mode": "intervals",
	    "output_bucket": "ct-my-bucket-out",
	    "output_file": "/output2/thumbs/test2_thumb.jpg",
	    "s3_rrs": true,
	    "size": "160x120",
	    "intervals": 5
	}
    ]
}

=== bfansports/CloudTranscode/input_samples/input_thumbs1.json
{
    "api_key": "1234567890abcdefghijkl",
    "input_type": "VIDEO",
    "input_bucket": "ct-my-bucket-in",
    "input_file": "/input1/test1.mp4",
    "job_label": "test1 thumbnails",
    "outputs": [
	{
	    "output_type": "THUMB",
	    "mode": "snapshot",
	    "output_bucket": "ct-my-bucket-out",
	    "output_file": "/output1/thumbs/test1_thumb.png",
	    "s3_rrs": true,
	    "size": "160x120",
	    "snapshot_sec": 5
	}
    ]
}
