=== bfansports/CloudTranscode/json_schemas/activities/TranscodeAsset.json
{
    "id": "http://sport-archive.com/input-schema/TranscodeAsset#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Schema for TranscodeAsset activity task",
    "type": "object",
    "properties": {
	"client": {
            "$ref": "client.json"
        },
        "input_json": {
            "description": "Original JSON input submitted to the Workflow",
            "type": "object"
        },
        "input_asset_type": {
            "description": "Type of the input asset",
            "type": "string",
	    "enum": [ "VIDEO", "AUDIO", "IMG", "DOC" ]
        },
        "input_asset_info": {
            "description": "Information about the input file to transcode",
            "type": "object",
            "properties": {
                "duration": { "type": "number" },
                "vcodec": { "type": "string" },
                "color": { "type": "string" },
                "size": { "type": "string" },
                "vbitrate": { "type": "string" },
                "fps": { "type": "string" },
                "ratio": { "type": "string" },
                "acodec": { "type": "string" },
                "freq": { "type": "string" },
                "mode": { "type": "string" },
                "abitrate": { "type": "string" }
            }
        },
        "output": {
            "$ref": "activities/output/base.json",
            "oneOf": [                    
                { "$ref": "activities/output/video.json" },
		{ "$ref": "activities/output/thumb.json" }
            ]
        }
    },
    "required": ["output", "input_asset_type", "input_asset_info", "input_json"],
    "additionalProperties": true
}

=== bfansports/CloudTranscode/input_samples/test_transcodeActivity_input.json
{
    "input_json": {
        "api_key": "1234567890abcdefghijkl",
        "input_type": "VIDEO",
        "input_bucket": "ct-my-bucket-in",
        "input_file": "/input1/test1.mp4",
        "job_label": "test1 transcode",
        "outputs": [
            {
		"output_type": "THUMB",
		"mode": "snapshot",
		"output_bucket": "ct-my-bucket-out",
		"output_file": "/output1/thumbs/test1_thumb.png",
		"s3_rrs": true,
		"size": "160x120",
		"snapshot_sec": 5
	    }
        ]
    },
    "input_asset_type": "VIDEO",
    "input_asset_info": {
        "duration": 25.05,
        "vcodec": "h264",
        "color": "yuv420p",
        "size": "480x360",
        "vbitrate": "640 kb/s",
        "fps": "30 fps",
        "ratio": "1.3",
        "acodec": "aac",
        "freq": "44100 Hz",
        "mode": "mono",
        "abitrate": "72 kb/s"
    },
    "output": {
        "output_type": "THUMB",
	"mode": "snapshot",
	"output_bucket": "ct-my-bucket-out",
	"output_file": "/output1/thumbs/test1_thumb.png",
	"s3_rrs": true,
	"size": "160x120",
	"snapshot_sec": 5
    }
}
